cloud:
  group: Base
  name: storageserver
  logo: assets/logo.png
  version: latest
  changelist: Changelist.md
  lang: cpp
  description: >-
    The storage service of key value mode is implemented based on raft, which
    can realize the data consistency of multiple machines (greater than or equal
    to 3 machines)
  description_cn: >-
    使用raft, rocksdb, tars服务构建的存储服务, 至少3节点, 可以保证多节点的数据的一致性.
  collaborators:
    - ruanshudong@qq.com
  repository: https://github.com/TarsCloudMarket/StorageServer.git
  readme: README.en.md
  readme_cn: README.md
  protocols:
    - tars/Storage.tars
  assets: 
    - assets
  open_source: false
  independent: true
app: Base 
server: StorageServer
template: tars.cpp
profile: ''
servants:
  - name: RaftObj
    port: 10000
    isTars: true
    isTcp: true
    thread: 2
    capacity: 100000
    connection: 10000
    timeout: 30000
  - name: StorageObj
    port: 20000
    isTars: true
    isTcp: true
    thread: 5
    capacity: 100000
    connection: 100000
    timeout: 60000
replicas: 3
hostNetwork: false
hostIPC: false
hostPorts: []
repo:
  id: null
  image: docker.tarsyun.com/tars/storageserver:latest
  secret: cloud-market-secret
mounts:
  - name: storage-data
    mountPath: /storage-data
    source:
      tLocalVolume: {}
config:
  - name: storage.conf
    content: |
      <root>
        <raft>
          	electionTimeoutMilliseconds = 3000
            heartbeatPeriodMilliseconds = 300
            snapshotPeriodSeconds       = 6000
            maxLogEntriesPerRequest     = 100
            maxLogEntriesMemQueue       = 3000
            maxLogEntriesTransfering    = 1000
        </raft>
        storage-path=/storage-data
      </root>
