name: build-base-compiler-master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.tarsyun.com
          username: ${{ secrets.name }}
          password: ${{ secrets.pass }}
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.MY_TOKEN }}
      - name: Create Build
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
          docker buildx create --name k8s-framework-builder --use
          docker buildx inspect --bootstrap --builder k8s-framework-builder
      - name: Buildx
        run: |
          docker run -v `pwd`:/data --entrypoint "" tarscloud/base-deploy sh -c "cd /data && /usr/bin/create-buildx-dockerfile.sh cpp yaml/values.yaml latest Dockerfile"
      - name: Create Docker
        run: |
          ./docker-buildx-cloud.sh
