name: build-base-compiler-master

on:
  push:
    tags:
      - v* 
      
jobs:
  build:
    container: tarscloud/base-compiler
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get version
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.tarsyun.com
          username: ${{ secrets.name }}
          password: ${{ secrets.pass }}
      - name: Cache build modules
        uses: actions/cache@v2
        env:
          cache-name: cache-build-modules
        with:
          path: build
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTION_DEPLOY_KEY }} 
          known_hosts: ${{ secrets.ACTION_KNOWN_HOSTS }} 
      - name: make
        run: mkdir -p build && cd build && cmake .. && make -j8
      - name: build docker
        run: |
          exec-build-cloud.sh tarscloud/tars.cppbase cpp build/bin/StorageServer yaml/values.yaml ${{ steps.get_version.outputs.VERSION }}  true